name: Pytests

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTEST_RUN_PATH: src/Engine

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Cache pip and uv venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            src/Engine/.venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}-engine
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip & install uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv

      - name: Run tests with uv (Engine dir)
        working-directory: src/Engine
        run: |
          uv sync || true
          uv run pytest -q
